### ISSUE TITLE
MNT: Stop using ci-helpers in appveyor.yml

### ISSUE THREAD

**Issue by pllim** [MSeifert04/numbamisc#6]
To whom it may concern,

If you are using https://github.com/astropy/ci-helpers in your appveyor.yml , please know that the Astropy project has dropped active development/support for Appveyor CI. If it still works, good for you, because we did not remove the relevant files (yet). But if it ever stops working, we have no plans to fix anything for Appveyor CI. Please consider using native Windows support other CI, e.g., Travis CI (see https://docs.travis-ci.com/user/reference/windows/). We apologize for any inconvenience caused.

If this issue is opened in error or irrelevant to you, feel free to close. Thank you.

xref astropy/ci-helpers#464

**Comment by MSeifert04** [comment]
Hey @pllim, nice to hear from you 👋 

This repo was never more than a proof-of-conept - so I removed the AppVeyor/Travis configs and hooks.

Thanks for dropping by.

**Comment by pllim** [comment]
Hello! Hope you are doing well. Haven't seen you around Astropy lately. :)

**Comment by MSeifert04** [comment]
I'm doing fine. How about you?

Wow, time really flies ... I've resigned (or meant to resign) from the astropy team roles earlier this year. But I really didn't mean to abandon astropy completely. However this year I really haven't found much time for programming (outside of work) at all, and, wow, the year is almost over 😕

**Comment by pllim** [comment]
Thanks for asking. I am fine as well, all things considered. 😬 

It is understandable but still sad to hear. We miss you at the project. Do stop by and say hi on Slack once in a while. Wish you all the best and don't be a stranger! 😄
